quora_app/accounts/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

quora_app/quora_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),
]

quora_app/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=False)
    gender = models.CharField(max_length=10, null=True, blank=False)

quora_app/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
            "password1",
            "password2",
            "age",
            "gender",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
        )

quora_app/accounts/views.py
from django.urls import reverse_lazy
from django.views import generic

from .forms import CustomUserCreationForm


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("signup1")
    template_name = "signup.html"

quora_app/templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>

<body>
    {% block content %}
    <div class="h-screen flex flex-row items-center justify-center">
        <div class="h-full w-1/2 flex flex-col justify-center bg-[#B92B27] px-12">
            <h1 class="text-5xl text-white font-bold mb-2">Welcome to Quora !</h1>
            <p class="text-white">
                Join our vibrant community of knowledge seekers and sharers. Log in to Quora to explore a world of
                diverse questions and insightful answers. Whether you're here to learn, share your expertise, or connect
                with like-minded individuals, Quora is the place to be. Enter your credentials to unlock a world of
                curiosity and discovery. Let the knowledge journey begin!</p>
        </div>
        <div class="w-1/2 justify-center">
            <h1 class="text-center text-5xl font-bold mb-4 text-[#B92B27]">Quora</h1>
            <form method="post" class="max-w-md mx-auto pt-12 px-12 py-16 shadow-2xl rounded-sm">
                {% csrf_token %}
                <div class="mb-4">
                    <input type="text" name="username" maxlength="150" autofocus="" required="" id="id_username"
                        placeholder="Username" class="w-full px-3 py-1 border rounded-sm">
                </div>

                <div class="mb-4">
                    <input type="email" name="email" maxlength="254" id="id_email" placeholder="Email" required=""
                        class="w-full px-3 py-1 border rounded-sm">
                </div>

                <div class="mb-4">
                    <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1"
                        placeholder="Password" class="w-full px-3 py-1 border rounded-sm">
                </div>

                <div class="mb-4">
                    <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2"
                        placeholder="Confirm Password" class="w-full px-3 py-1 border rounded-sm">
                </div>

                <div class="mb-4">
                    <input type="number" name="age" min="0" max="100" required="" id="id_age" placeholder="Age"
                        class="w-full px-3 py-2 border rounded-sm">
                </div>

                <div class="mb-4">
                    <input type="text" name="gender" maxlength="10" required="" id="id_gender" placeholder="Gender"
                        class="w-full px-3 py-1 border rounded-sm">
                </div>

                <button type="submit" class="bg-[#B92B27] text-white px-4 py-2 rounded-sm w-full">Log In</button>
            </form>
        </div>
    </div>

    {% endblock content %}
</body>

</html>